import { TemplateType, LetterState, LetterTemplateMeta } from '../types';

export const templatesMeta: LetterTemplateMeta[] = [
  // A. Kerja / Kantor
  {
    id: 'izin_tidak_masuk_kerja',
    category: 'kerja',
    categoryLabel: 'Keperluan Kerja / Kantor',
    title: 'Surat Izin Tidak Masuk Kerja',
    subtitle: 'Sakit, acara keluarga mendadak, atau kepentingan mendesak',
    defaultPerihal: 'Permohonan Izin Tidak Masuk Kerja',
  },
  {
    id: 'pengunduran_diri',
    category: 'kerja',
    categoryLabel: 'Keperluan Kerja / Kantor',
    title: 'Surat Pengunduran Diri (Resign)',
    subtitle: 'Pengunduran diri profesional & sopan sesuai standar korporat',
    defaultPerihal: 'Surat Pengunduran Diri dari Perusahaan',
  },
  {
    id: 'permohonan_cuti',
    category: 'kerja',
    categoryLabel: 'Keperluan Kerja / Kantor',
    title: 'Surat Permohonan Cuti',
    subtitle: 'Cuti tahunan, cuti melahirkan, atau cuti alasan penting',
    defaultPerihal: 'Permohonan Cuti Tahunan',
  },
  {
    id: 'penolakan_tawaran_kerja',
    category: 'kerja',
    categoryLabel: 'Keperluan Kerja / Kantor',
    title: 'Surat Penolakan Tawaran Kerja',
    subtitle: 'Penolakan tawaran kerja secara profesional dan etis',
    defaultPerihal: 'Konfirmasi Penolakan Tawaran Pekerjaan',
  },

  // B. Sekolah / Kampus
  {
    id: 'izin_tidak_masuk_sekolah',
    category: 'sekolah',
    categoryLabel: 'Keperluan Sekolah / Kampus',
    title: 'Surat Izin Tidak Masuk Sekolah/Kuliah',
    subtitle: 'Izin sakit atau berhalangan hadir untuk siswa/mahasiswa',
    defaultPerihal: 'Surat Izin Tidak Masuk Sekolah',
  },
  {
    id: 'cuti_akademik',
    category: 'sekolah',
    categoryLabel: 'Keperluan Sekolah / Kampus',
    title: 'Surat Permohonan Cuti Akademik',
    subtitle: 'Pengajuan cuti kuliah / penundaan semester sementara',
    defaultPerihal: 'Permohonan Cuti Akademik Semester',
  },
  {
    id: 'surat_pernyataan_ortu',
    category: 'sekolah',
    categoryLabel: 'Keperluan Sekolah / Kampus',
    title: 'Surat Keterangan / Pernyataan Orang Tua',
    subtitle: 'Pernyataan izin kegiatan / tanggungan biaya sekolah',
    defaultPerihal: 'Surat Pernyataan Orang Tua / Wali Murid',
  },

  // C. Pernyataan / Umum
  {
    id: 'keterangan_domisili',
    category: 'umum',
    categoryLabel: 'Surat Pernyataan / Umum',
    title: 'Surat Keterangan Domisili Mandiri',
    subtitle: 'Pernyataan tempat tinggal tetap untuk keperluan administratif',
    defaultPerihal: 'Surat Keterangan Domisili Tempat Tinggal',
  },
  {
    id: 'pernyataan_belum_menikah',
    category: 'umum',
    categoryLabel: 'Surat Pernyataan / Umum',
    title: 'Surat Pernyataan Belum Menikah (Lajang)',
    subtitle: 'Pernyataan status pernikahan untuk syarat pekerjaan / instansi',
    defaultPerihal: 'Surat Pernyataan Belum Menikah',
  },
  {
    id: 'pernyataan_penghasilan',
    category: 'umum',
    categoryLabel: 'Surat Pernyataan / Umum',
    title: 'Surat Pernyataan Penghasilan',
    subtitle: 'Pernyataan nominal gaji/pendapatan untuk beasiswa/KPR',
    defaultPerihal: 'Surat Pernyataan Besar Penghasilan',
  },
];

export const quickReasonPresets: Record<TemplateType, string[]> = {
  izin_tidak_masuk_kerja: [
    'Sakit (Disertai Surat Keterangan Dokter)',
    'Keperluan Keluarga Mendadak / Duka Cita',
    'Menghadiri Urusan Penting yang Tidak Dapat Ditinggalkan',
  ],
  pengunduran_diri: [
    'Mendapatkan Kesempatan Karier Baru di Tempat Lain',
    'Alasan Keluarga dan Pengembangan Usaha Mandiri',
    'Alasan Kesehatan dan Pemulihan Jangka Panjang',
  ],
  permohonan_cuti: [
    'Keperluan Keluarga Mendesak (Pernikahan / Khitanan)',
    'Cuti Tahunan untuk Istirahat dan Rekreasi',
    'Menjalankan Ibadah Keagamaan / Ziarah',
  ],
  penolakan_tawaran_kerja: [
    'Menerima Tawaran di Perusahaan Lain yang Lebih Sesuai',
    'Pertimbangan Jarak Lokasi dan Komuter',
    'Belum Dapat Menerima Tanggung Jawab pada Waktu Dekat',
  ],
  izin_tidak_masuk_sekolah: [
    'Sakit Demam dan Batuk (Perlu Istirahat Total 2 Hari)',
    'Menghadiri Acara Keluarga (Pernikahan Kakak Kandung)',
    'Mengikuti Kompetisi / Lomba Mewakili Sekolah',
  ],
  cuti_akademik: [
    'Kendala Finansial dan Persiapan Biaya Kuliah Semester Depan',
    'Keperluan Keluarga Mendesak di Luar Kota',
    'Mengikuti Program Magang / Internship Industri',
  ],
  surat_pernyataan_ortu: [
    'Memberikan Izin Penuh Mengikuti Kegiatan Studi Tour / Ekstrakurikuler',
    'Menanggung Segala Pembiayaan Selama Masa Pendidikan',
    'Menyetujui Keikutsertaan dalam Program Pelatihan Kampus',
  ],
  keterangan_domisili: [
    'Bertempat tinggal tetap di alamat tersebut selama lebih dari 5 tahun',
    'Pindah domisili baru dari luar kota untuk keperluan kerja',
  ],
  pernyataan_belum_menikah: [
    'Belum pernah menikah siri maupun tercatat di KUA / Catatan Sipil',
    'Berstatus lajang dan tanggungan mandiri',
  ],
  pernyataan_penghasilan: [
    'Penghasilan rata-rata Rp 4.500.000 per bulan untuk syarat beasiswa anak',
    'Pendapatan sektor informal mandiri untuk pengajuan perbankan',
  ],
};

export const presets: Record<TemplateType, Partial<LetterState>> = {
  izin_tidak_masuk_kerja: {
    templateType: 'izin_tidak_masuk_kerja',
    kotaTanggal: 'Jakarta, 4 September 2026',
    nomorSurat: '012/ITM/IX/2026',
    lampiran: '1 Lembar (Surat Dokter)',
    perihal: 'Permohonan Izin Tidak Masuk Kerja',
    kepadaNama: 'Bapak Rahmat Hidayat, S.T.',
    kepadaJabatan: 'HRD Manager',
    kepadaInstansi: 'PT. Nusantara Teknologi Solusi',
    kepadaAlamat: 'Gedung Cyber 2, Lantai 15, Jl. H.R. Rasuna Said, Jakarta Selatan',
    pengirimNama: 'Dewi Lestari, S.Kom.',
    pengirimId: 'NIK. 199408122018032001',
    pengirimJabatan: 'Software Quality Assurance Engineer',
    pengirimAlamat: 'Jl. Margonda Raya No. 45, Depok, Jawa Barat',
    pengirimTelepon: '+62 812-3456-7890',
    pengirimEmail: 'dewi.lestari@nawaliocorp.id',
    tanggalMulai: '2026-09-07',
    tanggalSelesai: '2026-09-08',
    alasanKategori: 'Sakit (Disertai Surat Keterangan Dokter)',
    alasanDetail: 'Mengalami demam tinggi dan infeksi tenggorokan berdasarkan anjuran dokter untuk beristirahat total selama dua hari.',
    namaPengganti: 'Ahmad Fauzi (Senior QA)',
  },
  pengunduran_diri: {
    templateType: 'pengunduran_diri',
    kotaTanggal: 'Surabaya, 4 September 2026',
    nomorSurat: '045/HR-RES/IX/2026',
    lampiran: '-',
    perihal: 'Surat Pengunduran Diri dari Perusahaan',
    kepadaNama: 'Ibu Dr. Dian Sastrowardoyo, M.B.A.',
    kepadaJabatan: 'Direktur Utama',
    kepadaInstansi: 'PT. Surya Semesta Abadi',
    kepadaAlamat: 'Jl. Pemuda No. 108, Surabaya, Jawa Timur',
    pengirimNama: 'Budi Santoso, S.E.',
    pengirimId: 'NIK. 199002152015011002',
    pengirimJabatan: 'Senior Financial Analyst',
    pengirimAlamat: 'Jl. Darmo Permai Selatan III/12, Surabaya',
    pengirimTelepon: '+62 813-9876-5432',
    pengirimEmail: 'budi.santoso@email.co.id',
    tanggalMulai: '2026-10-04',
    tanggalSelesai: '',
    alasanKategori: 'Alasan Keluarga dan Pengembangan Usaha Mandiri',
    alasanDetail: 'Keputusan ini saya ambil karena harus mendampingi orang tua di luar kota sekaligus merintis usaha keluarga yang memerlukan perhatian penuh.',
    namaPengganti: 'Siti Rahmawati, S.E. (Junior Analyst)',
  },
  permohonan_cuti: {
    templateType: 'permohonan_cuti',
    kotaTanggal: 'Bandung, 4 September 2026',
    nomorSurat: '089/CUTI/IX/2026',
    lampiran: '-',
    perihal: 'Permohonan Cuti Tahunan',
    kepadaNama: 'Bapak Ir. Hendra Gunawan',
    kepadaJabatan: 'Kepala Divisi Operasional',
    kepadaInstansi: 'PT. Bandung Raya Logistik',
    kepadaAlamat: 'Jl. Soekarno-Hatta No. 512, Bandung',
    pengirimNama: 'Rizky Pratama, S.T.',
    pengirimId: 'NIP. 199611202021041003',
    pengirimJabatan: 'Logistics Supervisor',
    pengirimAlamat: 'Jl. Buah Batu No. 120, Bandung',
    pengirimTelepon: '+62 821-1122-3344',
    pengirimEmail: 'rizky.pratama@logistik.id',
    tanggalMulai: '2026-09-15',
    tanggalSelesai: '2026-09-19',
    alasanKategori: 'Keperluan Keluarga Mendesak (Pernikahan / Khitanan)',
    alasanDetail: 'Melaksanakan cuti tahunan hak karyawan untuk menghadiri prosesi pernikahan adik kandung di Yogyakarta.',
    namaPengganti: 'Fajar Nugraha (Asisten Supervisor)',
  },
  penolakan_tawaran_kerja: {
    templateType: 'penolakan_tawaran_kerja',
    kotaTanggal: 'Jakarta, 4 September 2026',
    nomorSurat: '003/REJ/IX/2026',
    lampiran: '-',
    perihal: 'Konfirmasi Penolakan Tawaran Pekerjaan',
    kepadaNama: 'Ibu Sarah Wijaya, M.Psi.',
    kepadaJabatan: 'Talent Acquisition Lead',
    kepadaInstansi: 'PT. Global Digital Inovasi',
    kepadaAlamat: 'SCBD Lot 28, Jakarta Selatan',
    pengirimNama: 'Arya Wiguna, S.Kom.',
    pengirimId: 'KTP. 317105... [Opsional]',
    pengirimJabatan: 'Senior Software Engineer',
    pengirimAlamat: 'Jl. Tebet Raya No. 14, Jakarta Selatan',
    pengirimTelepon: '+62 856-7788-9900',
    pengirimEmail: 'arya.wiguna@devmail.id',
    tanggalMulai: '',
    tanggalSelesai: '',
    alasanKategori: 'Menerima Tawaran di Perusahaan Lain yang Lebih Sesuai',
    alasanDetail: 'Setelah melalui pertimbangan yang matang dan diskusi mendalam dengan keluarga, dengan berat hati saya harus menyampaikan bahwa saya menerima tawaran posisi di tempat lain yang jalurnya lebih selaras dengan visi jangka panjang karier saya.',
    namaPengganti: '',
  },
  izin_tidak_masuk_sekolah: {
    templateType: 'izin_tidak_masuk_sekolah',
    kotaTanggal: 'Semarang, 4 September 2026',
    nomorSurat: '10/S-IZIN/IX/2026',
    lampiran: '1 Lembar',
    perihal: 'Surat Izin Tidak Masuk Sekolah',
    kepadaNama: 'Ibu Dra. Hj. Siti Aminah, M.Pd.',
    kepadaJabatan: 'Wali Kelas XII IPA 2',
    kepadaInstansi: 'SMA Negeri 1 Semarang',
    kepadaAlamat: 'Jl. Pemuda No. 149, Semarang',
    pengirimNama: 'Dimas Anggara',
    pengirimId: 'NISN. 0081234567',
    pengirimJabatan: 'Siswa Kelas XII IPA 2',
    pengirimAlamat: 'Jl. Pandanaran No. 88, Semarang',
    pengirimTelepon: '+62 819-0011-2233',
    pengirimEmail: 'dimas.anggara@student.sch.id',
    tanggalMulai: '2026-09-07',
    tanggalSelesai: '2026-09-07',
    alasanKategori: 'Sakit Demam dan Batuk (Perlu Istirahat Total 2 Hari)',
    alasanDetail: 'Mengalami kondisi badan panas tinggi dan dianjurkan dokter puskesmas untuk beristirahat di rumah.',
    namaPengganti: '',
  },
  cuti_akademik: {
    templateType: 'cuti_akademik',
    kotaTanggal: 'Malang, 4 September 2026',
    nomorSurat: '552/UNIM/AKD/IX/2026',
    lampiran: '2 Lembar Bukti Pendukung',
    perihal: 'Permohonan Cuti Akademik Semester Ganjil',
    kepadaNama: 'Prof. Dr. Ir. Bambang Prajogo, M.Sc.',
    kepadaJabatan: 'Dekan Fakultas Teknik',
    kepadaInstansi: 'Universitas Brawijaya',
    kepadaAlamat: 'Jl. Veteran, Malang, Jawa Timur',
    pengirimNama: 'Nabila Zahra',
    pengirimId: 'NIM. 235060100111025',
    pengirimJabatan: 'Mahasiswa S1 Teknik Informatika',
    pengirimAlamat: 'Jl. Joyo Utomo No. 15, Malang',
    pengirimTelepon: '+62 822-3344-5566',
    pengirimEmail: 'nabila.zahra@student.ub.ac.id',
    tanggalMulai: '2026-09-01',
    tanggalSelesai: '2027-02-28',
    alasanKategori: 'Kendala Finansial dan Persiapan Biaya Kuliah Semester Depan',
    alasanDetail: 'Mengajukan permohonan cuti resmi selama 1 semester untuk pemulihan ekonomi keluarga dan membantu merawat orang tua.',
    namaPengganti: '',
  },
  surat_pernyataan_ortu: {
    templateType: 'surat_pernyataan_ortu',
    kotaTanggal: 'Yogyakarta, 4 September 2026',
    nomorSurat: '01/SPW/IX/2026',
    lampiran: '-',
    perihal: 'Surat Pernyataan Izin Orang Tua / Wali',
    kepadaNama: 'Kepala Sekolah SMK Negeri 2 Yogyakarta',
    kepadaJabatan: 'Kepala Sekolah',
    kepadaInstansi: 'SMK Negeri 2 Yogyakarta',
    kepadaAlamat: 'Jl. A. M. Sangaji No. 47, Jetis, Yogyakarta',
    pengirimNama: 'Sutrisno, S.Pd. (Orang Tua / Wali)',
    pengirimId: 'NIK. 3471012205700001',
    pengirimJabatan: 'Wali Murid dari Ananda Fikri Haikal',
    pengirimAlamat: 'Jl. Monjali No. 102, Sleman, Yogyakarta',
    pengirimTelepon: '+62 811-255-6677',
    pengirimEmail: 'sutrisno.wali@gmail.com',
    tanggalMulai: '2026-09-10',
    tanggalSelesai: '2026-09-12',
    alasanKategori: 'Memberikan Izin Penuh Mengikuti Kegiatan Studi Tour / Ekstrakurikuler',
    alasanDetail: 'Memberikan izin sepenuhnya kepada anak kami untuk mengikuti kegiatan Prakerin / Studi Industri di Bandung.',
    namaPengganti: '',
    pernyataanJenis: 'izin_kegiatan',
    pernyataanDetail: 'Memberikan izin sepenuhnya kepada anak kami untuk mengikuti kegiatan wajib sekolah di luar kota.',
  },
  keterangan_domisili: {
    templateType: 'keterangan_domisili',
    kotaTanggal: 'Bogor, 4 September 2026',
    nomorSurat: '474.4/012/DOM/IX/2026',
    lampiran: '1 Lembar KTP & KK',
    perihal: 'Surat Keterangan Domisili Tempat Tinggal',
    kepadaNama: 'Ketua RT 03 / RW 05',
    kepadaJabatan: 'Pengurus Rukun Tetangga',
    kepadaInstansi: 'Kelurahan Baranangsiang, Bogor Timur',
    kepadaAlamat: 'Jl. Pajajaran No. 42, Bogor',
    pengirimNama: 'Ratna Kumala, S.Sos.',
    pengirimId: 'NIK. 3271034407980004',
    pengirimJabatan: 'Warga Tetap',
    pengirimAlamat: 'Jl. Pajajaran No. 42, RT 03 / RW 05, Baranangsiang, Bogor',
    pengirimTelepon: '+62 858-9900-1122',
    pengirimEmail: 'ratna.kumala@yahoo.com',
    tanggalMulai: '',
    tanggalSelesai: '',
    alasanKategori: 'Bertempat tinggal tetap di alamat tersebut selama lebih dari 5 tahun',
    alasanDetail: 'Menyatakan dengan sesungguhnya bahwa saya benar-benar berdomisili dan bertempat tinggal tetap di wilayah RT 03 / RW 05 Kelurahan Baranangsiang, Bogor Timur.',
    namaPengganti: '',
    pernyataanJenis: 'domisili',
    pernyataanDetail: 'Bertempat tinggal tetap di Jl. Pajajaran No. 42, Baranangsiang, Bogor Timur sejak tahun 2020 hingga saat ini.',
  },
  pernyataan_belum_menikah: {
    templateType: 'pernyataan_belum_menikah',
    kotaTanggal: 'Medan, 4 September 2026',
    nomorSurat: '109/SPBM/IX/2026',
    lampiran: '2 Lembar',
    perihal: 'Surat Pernyataan Belum Pernah Menikah',
    kepadaNama: 'Kepala Bagian SDM / HRD',
    kepadaJabatan: 'Tim Rekrutmen Instansi',
    kepadaInstansi: 'PT. Perkebunan Nusantara (Persero)',
    kepadaAlamat: 'Jl. Letjend. S. Parman No. 107, Medan',
    pengirimNama: 'Fauzan Al-Ghifari, A.Md.',
    pengirimId: 'NIK. 1271051505010003',
    pengirimJabatan: 'Kandidat Pegawai Baru',
    pengirimAlamat: 'Jl. Dr. Mansur No. 50, Medan, Sumatera Utara',
    pengirimTelepon: '+62 813-6677-8899',
    pengirimEmail: 'fauzan.alghifari@outlook.com',
    tanggalMulai: '',
    tanggalSelesai: '',
    alasanKategori: 'Belum pernah menikah siri maupun tercatat di KUA / Catatan Sipil',
    alasanDetail: 'Menyatakan dengan sesungguhnya bahwa sampai dengan diterbitkannya surat pernyataan ini, saya berstatus belum pernah menikah dengan siapapun baik secara hukum agama maupun hukum negara.',
    namaPengganti: '',
    pernyataanJenis: 'belum_menikah',
    pernyataanDetail: 'Berstatus lajang / belum pernah menikah siri maupun tercatat resmi di Kantor Urusan Agama (KUA) atau Kantor Catatan Sipil.',
  },
  pernyataan_penghasilan: {
    templateType: 'pernyataan_penghasilan',
    kotaTanggal: 'Denpasar, 4 September 2026',
    nomorSurat: '304/SPP/IX/2026',
    lampiran: '1 Lembar',
    perihal: 'Surat Pernyataan Besar Penghasilan',
    kepadaNama: 'Panitia Beasiswa Prestasi',
    kepadaJabatan: 'Ketua Tim Seleksi Beasiswa',
    kepadaInstansi: 'Yayasan Peduli Pendidikan Indonesia',
    kepadaAlamat: 'Jl. Sunset Road No. 88, Kuta, Bali',
    pengirimNama: 'Wayan Sudarma',
    pengirimId: 'NIK. 5171011212820005',
    pengirimJabatan: 'Wiraswasta / Pekerja Lepas',
    pengirimAlamat: 'Jl. Raya Sesetan No. 12, Denpasar Selatan, Bali',
    pengirimTelepon: '+62 819-9988-7766',
    pengirimEmail: 'wayan.sudarma@bali.net',
    tanggalMulai: '',
    tanggalSelesai: '',
    alasanKategori: 'Penghasilan rata-rata Rp 4.500.000 per bulan untuk syarat beasiswa anak',
    alasanDetail: 'Menyatakan bahwa penghasilan rata-rata saya sebagai pekerja mandiri adalah sebesar Rp 4.500.000,- (Empat Juta Lima Ratus Ribu Rupiah) setiap bulannya.',
    namaPengganti: '',
    pernyataanJenis: 'penghasilan',
    pernyataanDetail: 'Memiliki penghasilan bersih rata-rata sebesar Rp 4.500.000,- (Empat Juta Lima Ratus Ribu Rupiah) per bulan.',
  },
};
